export interface Resource {
  id: string
  title: string
  url: string
  description: string
  type: 'book' | 'video' | 'tool' | 'paper' | 'course'
  tags: string[]
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  duration: string
}

export const RESOURCES: Resource[] = [
  {
    id: 'code-book',
    title: 'The Code Book',
    url: 'https://www.simonsingh.net/The_Code_Book/',
    description: 'A fascinating history of cryptography from ancient times to quantum cryptography, written for a general audience.',
    type: 'book',
    tags: ['history', 'classical', 'modern'],
    difficulty: 'beginner',
    duration: '~12 hours',
  },
  {
    id: 'serious-crypto',
    title: 'Serious Cryptography',
    url: 'https://nostarch.com/seriouscryptography',
    description: 'A practical introduction to modern encryption with code examples and mathematical foundations.',
    type: 'book',
    tags: ['practical', 'modern', 'implementation'],
    difficulty: 'intermediate',
    duration: '~15 hours',
  },
  {
    id: 'crypto-engineering',
    title: 'Cryptography Engineering',
    url: 'https://www.schneier.com/books/cryptography-engineering/',
    description: 'Design principles and best practices for building secure cryptographic systems by Ferguson, Schneier, and Kohno.',
    type: 'book',
    tags: ['engineering', 'protocols', 'practical'],
    difficulty: 'advanced',
    duration: '~20 hours',
  },
  {
    id: 'boneh-coursera',
    title: 'Cryptography I',
    url: 'https://www.coursera.org/learn/crypto',
    description: 'Dan Boneh\'s comprehensive Stanford course covering symmetric and asymmetric cryptography with rigorous mathematical foundations.',
    type: 'course',
    tags: ['university', 'mathematical', 'comprehensive'],
    difficulty: 'intermediate',
    duration: '~30 hours',
  },
  {
    id: 'cryptopals',
    title: 'Cryptopals Crypto Challenges',
    url: 'https://cryptopals.com/',
    description: 'A series of hands-on programming challenges covering real-world cryptographic attacks and implementations.',
    type: 'tool',
    tags: ['challenges', 'hands-on', 'attacks'],
    difficulty: 'intermediate',
    duration: 'self-paced',
  },
  {
    id: 'cyberchef',
    title: 'CyberChef',
    url: 'https://gchq.github.io/CyberChef/',
    description: 'The Cyber Swiss Army Knife — a web app for encryption, encoding, compression, and data analysis built by GCHQ.',
    type: 'tool',
    tags: ['encoding', 'analysis', 'practical'],
    difficulty: 'beginner',
    duration: 'self-paced',
  },
  {
    id: 'numberphile-crypto',
    title: 'Numberphile Cryptography Videos',
    url: 'https://www.youtube.com/playlist?list=PLt5AfwLPrxEK2Y0b3bI4aSbmF3DSRqHWH',
    description: 'Engaging short videos explaining cryptographic concepts from RSA to elliptic curves with visual demonstrations.',
    type: 'video',
    tags: ['visual', 'intuitive', 'history'],
    difficulty: 'beginner',
    duration: '~3 hours',
  },
  {
    id: 'computerphile-crypto',
    title: 'Computerphile Cryptography',
    url: 'https://www.youtube.com/playlist?list=PLzH6n4zXuckp7WH4J5F4UiVK0TYnRnI0I',
    description: 'Short deep dives into cryptographic topics by computer science professors, including AES, SHA-3, and zero-knowledge proofs.',
    type: 'video',
    tags: ['educational', 'algorithm', 'deep-dive'],
    difficulty: 'beginner',
    duration: '~4 hours',
  },
  {
    id: 'rijndael-paper',
    title: 'AES Proposal: Rijndael',
    url: 'https://csrc.nist.gov/csrc/media/projects/cryptographic-standards-and-guidelines/documents/aes-development/rijndael-ammended.pdf',
    description: 'The original Rijndael submission by Daemen and Rijmen that became the AES standard, with full design rationale.',
    type: 'paper',
    tags: ['design', 'symmetric', 'standard'],
    difficulty: 'advanced',
    duration: '~8 hours',
  },
  {
    id: 'sha3-paper',
    title: 'SHA-3 Standard: Permutation-Based Hash',
    url: 'https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.202.pdf',
    description: 'The official NIST FIPS 202 standard for SHA-3, describing the Keccak sponge construction.',
    type: 'paper',
    tags: ['hash', 'standard', 'sponge'],
    difficulty: 'advanced',
    duration: '~6 hours',
  },
  {
    id: 'applied-crypto',
    title: 'Applied Cryptography',
    url: 'https://www.schneier.com/books/applied-cryptography/',
    description: 'Bruce Schneier\'s comprehensive reference covering protocol design, algorithms, and source code for cryptographic systems.',
    type: 'book',
    tags: ['reference', 'protocols', 'source-code'],
    difficulty: 'advanced',
    duration: '~30 hours',
  },
  {
    id: 'crypto-101',
    title: 'Crypto 101',
    url: 'https://www.crypto101.io/',
    description: 'A free introductory course on cryptography with interactive examples and clear explanations of core concepts.',
    type: 'course',
    tags: ['free', 'interactive', 'beginner-friendly'],
    difficulty: 'beginner',
    duration: '~8 hours',
  },
  {
    id: 'ecc-talk',
    title: 'Elliptic Curve Cryptography (ECC) — A Visual Introduction',
    url: 'https://curves.xargs.org/',
    description: 'An interactive visual guide to elliptic curves and how they are used in cryptography.',
    type: 'tool',
    tags: ['visual', 'ecc', 'interactive'],
    difficulty: 'intermediate',
    duration: 'self-paced',
  },
  {
    id: 'cryptography-stackexchange',
    title: 'Cryptography Stack Exchange',
    url: 'https://crypto.stackexchange.com/',
    description: 'A Q&A community for cryptography researchers and practitioners with high-quality discussions and expert answers.',
    type: 'tool',
    tags: ['community', 'qanda', 'reference'],
    difficulty: 'beginner',
    duration: 'self-paced',
  },
  {
    id: 'aes-illustrated',
    title: 'AES — The Advanced Encryption Standard Illustrated',
    url: 'https://www.moserware.com/2009/09/stick-figure-guide-to-advanced.html',
    description: 'A humorous yet technically accurate stick-figure guide walking through every step of AES encryption.',
    type: 'video',
    tags: ['visual', 'aes', 'humorous'],
    difficulty: 'beginner',
    duration: '~1 hour',
  },
  {
    id: 'pqc-competition',
    title: 'NIST Post-Quantum Cryptography Standardization',
    url: 'https://csrc.nist.gov/projects/post-quantum-cryptography',
    description: 'NIST\'s ongoing effort to standardize quantum-resistant cryptographic algorithms, including CRYSTALS-Kyber and Dilithium.',
    type: 'paper',
    tags: ['quantum', 'standardization', 'future'],
    difficulty: 'advanced',
    duration: '~10 hours',
  },
  {
    id: 'tls-13-rfc',
    title: 'RFC 8446 — TLS 1.3',
    url: 'https://datatracker.ietf.org/doc/html/rfc8446',
    description: 'The official specification for TLS 1.3, the modern secure transport protocol using hybrid cryptography.',
    type: 'paper',
    tags: ['protocol', 'standards', 'tls'],
    difficulty: 'intermediate',
    duration: '~5 hours',
  },
  {
    id: 'open-ssl-tool',
    title: 'OpenSSL Cookbook',
    url: 'https://www.feistyduck.com/books/openssl-cookbook/',
    description: 'A practical guide to using OpenSSL for certificate management, encryption, and TLS configuration.',
    type: 'book',
    tags: ['practical', 'tooling', 'certificates'],
    difficulty: 'intermediate',
    duration: '~8 hours',
  },
  {
    id: 'crypto-hack',
    title: 'CryptoHack',
    url: 'https://cryptohack.org/',
    description: 'A gamified platform with cryptography challenges ranging from classic ciphers to modern elliptic curve attacks.',
    type: 'tool',
    tags: ['challenges', 'gamified', 'ctf'],
    difficulty: 'intermediate',
    duration: 'self-paced',
  },
  {
    id: 'modern-crypto-daniele',
    title: 'A Graduate Course in Applied Cryptography',
    url: 'https://toc.cryptobook.us/',
    description: 'Free online textbook by Boneh and Shoup covering modern cryptography with rigorous proofs and practical constructions.',
    type: 'book',
    tags: ['graduate', 'rigorous', 'comprehensive'],
    difficulty: 'advanced',
    duration: '~40 hours',
  },
  {
    id: 'diffie-hellman-paper',
    title: 'New Directions in Cryptography',
    url: 'https://ee.stanford.edu/~hellman/publications/24.pdf',
    description: 'The seminal 1976 paper by Diffie and Hellman that introduced public-key cryptography and digital signatures.',
    type: 'paper',
    tags: ['historical', 'foundational', 'public-key'],
    difficulty: 'intermediate',
    duration: '~2 hours',
  },
  {
    id: 'eff-rsa-factor',
    title: 'EFF RSA Factoring Challenge',
    url: 'https://en.wikipedia.org/wiki/RSA_Factoring_Challenge',
    description: 'The historical challenge that tracked the progress of integer factorization, demonstrating the security limits of RSA key sizes.',
    type: 'video',
    tags: ['history', 'factoring', 'challenge'],
    difficulty: 'beginner',
    duration: '~30 min',
  },
]
