export interface CipherDefinition {
  id: string
  name: string
  category: 'classical' | 'symmetric' | 'hash' | 'asymmetric'
  description: string
  defaultKey: string
  defaultInput: string
  securityStatus: 'secure' | 'legacy' | 'deprecated' | 'broken'
  keyPlaceholder?: string
  options?: {
    name: string
    id: string
    type: 'number' | 'text' | 'boolean' | 'select'
    default: any
    choices?: { label: string; value: any }[]
  }[]
}

export const CIPHER_REGISTRY: CipherDefinition[] = [
  // Classical
  {
    id: 'caesar',
    name: 'Caesar Cipher',
    category: 'classical',
    description: 'A simple shift substitution cipher where each letter in the plaintext is shifted by a fixed number of positions.',
    defaultKey: '3',
    defaultInput: 'Hello, World!',
    securityStatus: 'broken',
    keyPlaceholder: 'Shift (e.g. 3)',
  },
  {
    id: 'rot13',
    name: 'ROT13',
    category: 'classical',
    description: 'A special case of Caesar cipher with a fixed shift value of 13.',
    defaultKey: '',
    defaultInput: 'Hello, World!',
    securityStatus: 'broken',
  },
  {
    id: 'vigenere',
    name: 'Vigenère Cipher',
    category: 'classical',
    description: 'A polyalphabetic substitution cipher that uses a keyword to shift characters in repeating cycles.',
    defaultKey: 'LEMON',
    defaultInput: 'ATTACKATDAWN',
    securityStatus: 'broken',
    keyPlaceholder: 'Keyword (e.g. LEMON)',
  },
  {
    id: 'atbash',
    name: 'Atbash Cipher',
    category: 'classical',
    description: 'A monoalphabetic substitution cipher formed by reversing the alphabet (A becomes Z, B becomes Y, etc.).',
    defaultKey: '',
    defaultInput: 'Hello, World!',
    securityStatus: 'broken',
  },
  {
    id: 'playfair',
    name: 'Playfair Cipher',
    category: 'classical',
    description: 'A polygraphic substitution cipher that encrypts pairs of letters using a dynamic 5x5 key matrix.',
    defaultKey: 'PLAYFAIR EXAMPLE',
    defaultInput: 'HIDE THE GOLD IN THE TREE STUMP',
    securityStatus: 'broken',
    keyPlaceholder: 'Key phrase',
  },
  {
    id: 'railfence',
    name: 'Rail Fence Cipher',
    category: 'classical',
    description: 'A transposition cipher where plaintext is written diagonally down and up on successive "rails" of a fence.',
    defaultKey: '3',
    defaultInput: 'WE ARE DISCOVERED FLEE AT ONCE',
    securityStatus: 'broken',
    keyPlaceholder: 'Number of rails (e.g. 3)',
  },
  {
    id: 'polybius',
    name: 'Polybius Square',
    category: 'classical',
    description: 'Ancient Greek grid cipher encoding each letter as a (row, col) coordinate pair in a 5×5 grid. J is merged into I.',
    defaultKey: '',
    defaultInput: 'HELLO WORLD',
    securityStatus: 'legacy',
    keyPlaceholder: 'Optional keyword to key the grid (e.g. POLYBIUS)',
  },
  {
    id: 'beaufort',
    name: 'Beaufort Cipher',
    category: 'classical',
    description: 'A polyalphabetic substitution cipher that reverses the Vigenère formula (K - P instead of P + K), making it self-inverse.',
    defaultKey: 'BEAUFORT',
    defaultInput: 'HELLO WORLD',
    securityStatus: 'broken',
    keyPlaceholder: 'Keyword (e.g. BEAUFORT)',
  },
  {
    id: 'columnar-transposition',
    name: 'Columnar Transposition',
    category: 'classical',
    description: 'Keyed transposition cipher — plaintext is written in rows then columns are read in alphabetical key order.',
    defaultKey: 'ZEBRAS',
    defaultInput: 'WEAREDISCOVEREDFLEEAATONCE',
    securityStatus: 'legacy',
    keyPlaceholder: 'Alphabetic key (e.g. ZEBRAS)',
  },
  {
    id: 'hill',
    name: 'Hill Cipher',
    category: 'classical',
    description: 'A polygraphic substitution cipher that encrypts pairs of letters using 2x2 matrix multiplication modulo 26.',
    defaultKey: 'HILL',
    defaultInput: 'HELP',
    securityStatus: 'broken',
    keyPlaceholder: '4-letter key (e.g. HILL)',
  },
  {
    id: 'autokey',
    name: 'Autokey Vigenère',
    category: 'classical',
    description: 'A stronger variant of Vigenère where the keystream extends using the plaintext itself instead of repeating the key, removing Kasiski-style periodicity.',
    defaultKey: 'QUEENLY',
    defaultInput: 'ATTACKATDAWN',
    securityStatus: 'broken',
    keyPlaceholder: 'Keyword (e.g. QUEENLY)',
  },
  {
    id: 'porta',
    name: 'Porta Cipher',
    category: 'classical',
    description: 'A 1563 reciprocal polyalphabetic cipher that swaps letters between two 13-letter alphabet halves using a 13-row tableau — self-inverse like Beaufort.',
    defaultKey: 'PORTA',
    defaultInput: 'HELLO WORLD',
    securityStatus: 'broken',
    keyPlaceholder: 'Keyword (e.g. PORTA)',
  },
  {
    id: 'adfgvx',
    name: 'ADFGVX Cipher',
    category: 'classical',
    description: 'A WWI-era cipher combining a keyed 6x6 Polybius-square substitution with a keyed columnar transposition.',
    defaultKey: 'PICTURE,GERMAN',
    defaultInput: 'ATTACKAT1200AM',
    securityStatus: 'broken',
    keyPlaceholder: 'gridKey,transpositionKey (e.g. PICTURE,GERMAN)',
  },
  {
    id: 'bifid',
    name: 'Bifid Cipher',
    category: 'classical',
    description: 'A fractionating cipher combining a keyed Polybius-square substitution with a positional transposition across the whole message.',
    defaultKey: 'BIFID',
    defaultInput: 'HELLOWORLD',
    securityStatus: 'broken',
    keyPlaceholder: 'Optional keyword to key the grid (e.g. BIFID)',
  },
  {
    id: 'foursquare',
    name: 'Four-Square Cipher',
    category: 'classical',
    description: 'A polygraphic substitution cipher (Delastelle) that encrypts letter pairs using two keyed 5x5 grids alongside two standard alphabet grids.',
    defaultKey: 'EXAMPLE,KEYWORD',
    defaultInput: 'HELP ME OBI WAN KENOBI',
    securityStatus: 'broken',
    keyPlaceholder: 'key1,key2 (e.g. EXAMPLE,KEYWORD)',
  },
  {
    id: 'nihilist',
    name: 'Nihilist Cipher',
    category: 'classical',
    description: '19th-century Russian cipher combining a keyed Polybius square with additive (non-modular) numeric key stream addition — outputs numbers, not letters.',
    defaultKey: 'RUSSIAN,KEY',
    defaultInput: 'HELLO WORLD',
    securityStatus: 'broken',
    keyPlaceholder: 'squareKeyword,numericKeyword (e.g. RUSSIAN,KEY)',
  },
  // Symmetric
  {
    id: 'xor',
    name: 'XOR Cipher',
    category: 'symmetric',
    description: 'A simple stream cipher performing byte-wise XOR operations between plaintext and key.',
    defaultKey: 'secret',
    defaultInput: 'Hello, World!',
    securityStatus: 'deprecated',
    keyPlaceholder: 'Secret key string',
  },
  {
    id: 'otp',
    name: 'One-Time Pad (OTP)',
    category: 'symmetric',
    description: 'An unbreakable cipher when used with a truly random, single-use key of equal length to the plaintext.',
    defaultKey: 'supersecretkeystring',
    defaultInput: 'Hello, World!',
    securityStatus: 'secure',
    keyPlaceholder: 'Key (must match or exceed input length)',
  },
  {
    id: 'des',
    name: 'DES',
    category: 'symmetric',
    description: 'Data Encryption Standard. A legacy 64-bit block cipher utilizing a 56-bit key size.',
    defaultKey: '133457799BBCDDF1',
    defaultInput: '0123456789ABCDEF',
    securityStatus: 'broken',
    keyPlaceholder: '16-character hex key',
    options: [
      {
        name: 'Hex Input Mode',
        id: 'hexInput',
        type: 'boolean',
        default: true,
      },
    ],
  },
  {
    id: '3des',
    name: '3DES (Triple DES)',
    category: 'symmetric',
    description: 'Applies the DES algorithm three times to each data block with two or three keys to increase security.',
    defaultKey: '0123456789ABCDEF0123456789ABCDEF',
    defaultInput: 'Hello, World!',
    securityStatus: 'legacy',
    keyPlaceholder: '32-character hex key (2-Key) or 48-character (3-Key)',
    options: [
      {
        name: 'Hex Input Mode',
        id: 'hexInput',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    id: 'aes',
    name: 'AES',
    category: 'symmetric',
    description: 'Advanced Encryption Standard. A highly secure, standard block cipher supporting key sizes of 128, 192, or 256 bits.',
    defaultKey: '000102030405060708090a0b0c0d0e0f',
    defaultInput: '00112233445566778899aabbccddeeff',
    securityStatus: 'secure',
    keyPlaceholder: '32/48/64-character hex key',
    options: [
      {
        name: 'Hex Input Mode',
        id: 'hexInput',
        type: 'boolean',
        default: true,
      },
      {
        name: 'Mode of Operation',
        id: 'mode',
        type: 'select',
        default: 'ECB',
        choices: [
          { label: 'ECB (Electronic Codebook)', value: 'ECB' },
          { label: 'CBC (Cipher Block Chaining)', value: 'CBC' },
          { label: 'CTR (Counter)', value: 'CTR' },
          { label: 'CFB (Cipher Feedback)', value: 'CFB' },
          { label: 'OFB (Output Feedback)', value: 'OFB' },
        ],
      },
    ],
  },
  {
    id: 'aes-gcm',
    name: 'AES-GCM (AEAD)',
    category: 'symmetric',
    description: 'Authenticated encryption (AEAD): AES in counter mode for confidentiality plus a GHASH authentication tag for integrity. Used by TLS 1.3 and WireGuard — flipping a single ciphertext byte makes tag verification fail.',
    defaultKey: '000102030405060708090a0b0c0d0e0f',
    defaultInput: 'Integrity + confidentiality!',
    securityStatus: 'secure',
    keyPlaceholder: '32/48/64-char hex key (AES-128/192/256)',
  },
  {
    id: 'rc4',
    name: 'RC4',
    category: 'symmetric',
    description: 'A byte-oriented stream cipher combining a Key-Scheduling Algorithm (KSA) with a Pseudo-Random Generation Algorithm (PRGA) to produce a keystream.',
    defaultKey: 'Key',
    defaultInput: 'Plaintext',
    securityStatus: 'broken',
    keyPlaceholder: 'Secret key string (1-256 bytes)',
  },
  {
    id: 'salsa20',
    name: 'Salsa20',
    category: 'symmetric',
    description: 'A modern ARX-based stream cipher (Bernstein, 2005) built from add-rotate-XOR quarter-rounds — the direct predecessor to ChaCha20.',
    defaultKey: '0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000|0000000000000000',
    defaultInput: '48656c6c6f2c2053616c73613230',
    securityStatus: 'secure',
    keyPlaceholder: '64-char hex key | 16-char hex nonce',
  },
  {
    id: 'skipjack',
    name: 'Skipjack',
    category: 'symmetric',
    description: 'NSA Clipper-chip cipher, declassified 1998. Unbalanced Feistel network alternating two round functions (Rule A / Rule B) across 32 rounds.',
    defaultKey: '00998877665544332211',
    defaultInput: '33221100ddccbbaa',
    securityStatus: 'legacy',
    keyPlaceholder: '20-character hex key (80-bit)',
    options: [
      { name: 'Hex Input Mode', id: 'hexInput', type: 'boolean', default: true },
    ],
  },
  {
    id: 'chacha20',
    name: 'ChaCha20',
    category: 'symmetric',
    description: 'A modern ARX-based stream cipher (RFC 8439) used in TLS 1.3, built from add-rotate-XOR quarter-rounds instead of substitution boxes.',
    defaultKey: '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f|000000000000004a00000000:0',
    defaultInput: 'Hello, ChaCha20!',
    securityStatus: 'secure',
    keyPlaceholder: '64-char hex key | 24-char hex nonce [:counter]',
  },
  {
    id: 'rc5',
    name: 'RC5-32/12/16',
    category: 'symmetric',
    description: 'Parameterized Feistel-like cipher (Rivest, 1994) whose signature feature is data-dependent rotation — the rotation amount each round comes from the data itself, not a fixed schedule.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '0000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '32-character hex key (128-bit); fixed to 12 rounds / 64-bit block',
    options: [
      { name: 'Hex Input Mode', id: 'hexInput', type: 'boolean', default: true },
    ],
  },
  {
    id: 'xtea',
    name: 'XTEA',
    category: 'symmetric',
    description: 'A compact 64-round Feistel cipher (Wheeler & Needham, 1997) using only addition, XOR, and shifts — no lookup tables.',
    defaultKey: '000102030405060708090a0b0c0d0e0f',
    defaultInput: '4142434445464748',
    securityStatus: 'secure',
    keyPlaceholder: '32-character hex key (128-bit)',
  },
  {
    id: 'idea',
    name: 'IDEA',
    category: 'symmetric',
    description: 'Lai-Massey block cipher (used in PGP 2.0) mixing XOR, addition mod 2^16, and multiplication mod 2^16+1 across 8.5 rounds.',
    defaultKey: '000102030405060708090a0b0c0d0e0f',
    defaultInput: '0000000100020003',
    securityStatus: 'legacy',
    keyPlaceholder: '32-character hex key (128-bit)',
    options: [
      { name: 'Hex Input Mode', id: 'hexInput', type: 'boolean', default: true },
    ],
  },
  // Hash
  {
    id: 'sha256',
    name: 'SHA-256',
    category: 'hash',
    description: 'Secure Hash Algorithm 2. Produces a unique 256-bit (32-byte) hash output representing the input message.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'secure',
  },
  {
    id: 'sha512',
    name: 'SHA-512',
    category: 'hash',
    description: 'Secure Hash Algorithm 2 with 64-bit words, producing a secure 512-bit (64-byte) digest.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'secure',
  },
  {
    id: 'md5',
    name: 'MD5',
    category: 'hash',
    description: 'A widely used legacy hash producing a 128-bit output. Cryptographically broken due to collision vulnerabilities.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'broken',
  },
  {
    id: 'hmac',
    name: 'HMAC-SHA256',
    category: 'hash',
    description: 'Keyed-hash Message Authentication Code. Combines SHA-256 with a cryptographic secret key.',
    defaultKey: 'Jefe',
    defaultInput: 'what do ya want for nothing?',
    securityStatus: 'secure',
    keyPlaceholder: 'HMAC Secret Key',
  },
  {
    id: 'bcrypt',
    name: 'Bcrypt',
    category: 'hash',
    description: 'A password hashing function incorporating a salt and cost factor, designed to be slow to prevent brute force.',
    defaultKey: 'password',
    defaultInput: 'password',
    securityStatus: 'secure',
    options: [
      {
        name: 'Rounds (Cost)',
        id: 'rounds',
        type: 'number',
        default: 4,
      },
    ],
  },
  {
    id: 'sha3',
    name: 'SHA3-256',
    category: 'hash',
    description: 'NIST FIPS 202 hash function using the Keccak sponge construction — 24-round permutation over a 1600-bit state.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'secure',
  },
  {
    id: 'sha1',
    name: 'SHA-1',
    category: 'hash',
    description: 'Legacy 160-bit hash function (NIST FIPS 180-1). Cryptographically broken — SHAttered collision attack demonstrated in 2017.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'broken',
  },
  {
    id: 'ripemd160',
    name: 'RIPEMD-160',
    category: 'hash',
    description: 'A 160-bit hash function using two independent, parallel compression lines whose final states are combined by modular addition.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'legacy',
  },
  {
    id: 'blake2b',
    name: 'BLAKE2b-256',
    category: 'hash',
    description: 'RFC 7693 hash function — faster than MD5/SHA-2 while at least as secure as SHA-3, with a natively built-in keyed-MAC mode (no HMAC construction needed).',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'secure',
    keyPlaceholder: 'Optional MAC key (leave blank for plain hash)',
  },
  {
    id: 'poly1305',
    name: 'Poly1305',
    category: 'hash',
    description: 'One-time polynomial MAC over GF(2^130-5) (RFC 8439), originally paired with ChaCha20 for AEAD. Generates a tag; not reversible, same as SHA-3/SHA-1/RIPEMD-160.',
    defaultKey: '85d6be7857556d337f4452fe42d506a80103808afb0db2fd4abff6af4149f51b',
    defaultInput: '43727970746f6772617068696320466f72756d2052657365617263682047726f7570',
    securityStatus: 'secure',
    keyPlaceholder: '64-character hex key (32 bytes: r || s)',
    options: [
      { name: 'Hex Input Mode', id: 'hexInput', type: 'boolean', default: true },
    ],
  },
  // Asymmetric
  {
    id: 'rsa',
    name: 'RSA-2048',
    category: 'asymmetric',
    description: 'An asymmetric cipher based on the difficulty of factoring large semiprimes. Supports key generation, encryption, and decryption.',
    defaultKey: '61,53,17',
    defaultInput: 'HELLO',
    securityStatus: 'secure',
    keyPlaceholder: 'Enter: 3 values (p,q,e) or 2 values (n,e / n,d) if you already have n',
    options: [
      {
        name: 'Demo Mode (Small Primes)',
        id: 'demoMode',
        type: 'boolean',
        default: true,
      },
    ],
  },
  {
    id: 'dh',
    name: 'Diffie-Hellman',
    category: 'asymmetric',
    description: 'A key exchange protocol enabling two parties to establish a shared secret over an insecure channel.',
    defaultKey: '23,5',
    defaultInput: '6,15',
    securityStatus: 'secure',
    keyPlaceholder: 'p,g parameters (e.g. 23,5)',
    options: [
      {
        name: 'Bob Secret input (demo)',
        id: 'bobSecret',
        type: 'text',
        default: '15',
      },
    ],
  },
  {
    id: 'ecc',
    name: 'ECC (ECDSA P-256)',
    category: 'asymmetric',
    description: 'Elliptic Curve Cryptography. Implements ECDSA signing and verification over the NIST P-256 curve.',
    defaultKey: '0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20',
    defaultInput: 'hello',
    securityStatus: 'secure',
    keyPlaceholder: '32-byte private key hex (64 chars)',
  },
  {
    id: 'elgamal',
    name: 'ElGamal',
    category: 'asymmetric',
    description: 'A public-key encryption scheme based on the discrete logarithm problem, using ephemeral-key modular exponentiation.',
    defaultKey: '23,5,8',
    defaultInput: '4',
    securityStatus: 'secure',
    keyPlaceholder: 'p,g,y (prime, generator, public key)',
  },
  {
    id: 'ed25519',
    name: 'Ed25519 (EdDSA)',
    category: 'asymmetric',
    description: 'Edwards-curve Digital Signature Algorithm — deterministic signatures over Curve25519, with no external randomness and no nonce-reuse failure mode.',
    defaultKey: '',
    defaultInput: 'hello',
    securityStatus: 'secure',
    keyPlaceholder: '32-byte private key hex (64 chars), or leave blank to generate one',
  },
  {
    id: 'x25519',
    name: 'X25519',
    category: 'asymmetric',
    description: 'Elliptic-curve Diffie-Hellman key agreement over Curve25519 (RFC 7748) — the modern, rigid-curve alternative to classic Diffie-Hellman and NIST P-256 ECDH.',
    defaultKey: 'a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac',
    defaultInput: 'e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4',
    securityStatus: 'secure',
    keyPlaceholder: '32-byte private key hex (64 chars), or leave blank to generate one',
  },
  {
    id: 'merkle-hellman',
    name: 'Merkle–Hellman Knapsack',
    category: 'asymmetric',
    description: 'First public-key cryptosystem after RSA (1978), based on the subset-sum problem rather than factoring. Broken by Shamir (1984) via lattice reduction — kept for educational value.',
    defaultKey: '2,3,6,13,27,52,105,210,420,41',
    defaultInput: 'HI',
    securityStatus: 'broken',
    keyPlaceholder: 'superincreasing sequence,modulus,multiplier (e.g. 2,3,6,13,27,52,105,210,420,41)',
  },
]
