export type CipherOptionValue = string | number | boolean

export interface CipherDefinition {
  id: string;
  name: string;
  category: "classical" | "symmetric" | "hash" | "asymmetric";
  description: string;
  defaultKey: string;
  defaultInput: string;
  securityStatus: "secure" | "legacy" | "deprecated" | "broken";
  keyPlaceholder?: string;
  options?: {
    name: string;
    id: string;
    type: "number" | "text" | "boolean" | "select";
    default: CipherOptionValue;
    choices?: { label: string; value: CipherOptionValue }[];
  }[];
}

export const CIPHER_REGISTRY: CipherDefinition[] = [
  {
    id: "caesar",
    name: "Caesar Cipher",
    category: "classical",
    description:
      "A simple shift substitution cipher where each letter in the plaintext is shifted by a fixed number of positions.",
    defaultKey: "3",
    defaultInput: "Hello, World!",
    securityStatus: "broken",
    keyPlaceholder: "Shift (e.g. 3)",
  },
  {
    id: "rot13",
    name: "ROT13",
    category: "classical",
    description:
      "A special case of Caesar cipher with a fixed shift value of 13.",
    defaultKey: "",
    defaultInput: "Hello, World!",
    securityStatus: "broken",
  },
  {
    id: "vigenere",
    name: "Vigenère Cipher",
    category: "classical",
    description:
      "A polyalphabetic substitution cipher that uses a keyword to shift characters in repeating cycles.",
    defaultKey: "LEMON",
    defaultInput: "ATTACKATDAWN",
    securityStatus: "broken",
    keyPlaceholder: "Keyword (e.g. LEMON)",
  },
  {
    id: "atbash",
    name: "Atbash Cipher",
    category: "classical",
    description:
      "A monoalphabetic substitution cipher formed by reversing the alphabet (A becomes Z, B becomes Y, etc.).",
    defaultKey: "",
    defaultInput: "Hello, World!",
    securityStatus: "broken",
  },
  {
    id: "playfair",
    name: "Playfair Cipher",
    category: "classical",
    description:
      "A polygraphic substitution cipher that encrypts pairs of letters using a dynamic 5x5 key matrix.",
    defaultKey: "PLAYFAIR EXAMPLE",
    defaultInput: "HIDE THE GOLD IN THE TREE STUMP",
    securityStatus: "broken",
    keyPlaceholder: "Key phrase",
  },
  {
    id: "railfence",
    name: "Rail Fence Cipher",
    category: "classical",
    description:
      'A transposition cipher where plaintext is written diagonally down and up on successive "rails" of a fence.',
    defaultKey: "3",
    defaultInput: "WE ARE DISCOVERED FLEE AT ONCE",
    securityStatus: "broken",
    keyPlaceholder: "Number of rails (e.g. 3)",
  },
  {
    id: "xor",
    name: "XOR Cipher",
    category: "symmetric",
    description:
      "A simple stream cipher performing byte-wise XOR operations between plaintext and key.",
    defaultKey: "secret",
    defaultInput: "Hello, World!",
    securityStatus: "deprecated",
    keyPlaceholder: "Secret key string",
  },
  {
    id: "otp",
    name: "One-Time Pad (OTP)",
    category: "symmetric",
    description:
      "An unbreakable cipher when used with a truly random, single-use key of equal length to the plaintext.",
    defaultKey: "supersecretkeystring",
    defaultInput: "Hello, World!",
    securityStatus: "secure",
    keyPlaceholder: "Key (must match or exceed input length)",
  },
  {
    id: "des",
    name: "DES",
    category: "symmetric",
    description:
      "Data Encryption Standard. A legacy 64-bit block cipher utilizing a 56-bit key size.",
    defaultKey: "133457799BBCDDF1",
    defaultInput: "0123456789ABCDEF",
    securityStatus: "broken",
    keyPlaceholder: "16-character hex key",
    options: [
      {
        name: "Hex Input Mode",
        id: "hexInput",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "3des",
    name: "3DES (Triple DES)",
    category: "symmetric",
    description:
      "Applies the DES algorithm three times to each data block with two or three keys to increase security.",
    defaultKey: "0123456789ABCDEF0123456789ABCDEF",
    defaultInput: "Hello, World!",
    securityStatus: "deprecated",
    keyPlaceholder: "32-character hex key (2-Key) or 48-character (3-Key)",
    options: [
      {
        name: "Hex Input Mode",
        id: "hexInput",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: 'aes-xts',
    name: 'AES-XTS',
    category: 'symmetric',
    description: 'A tweakable mode (IEEE P1619) for disk-sector encryption, composed from the existing AES module — the sector number IS the tweak, so no IV needs to be stored per sector. Confidentiality-only, no authentication tag (unlike AES-GCM).',
    defaultKey: '2b7e151628aed2a6abf7158809cf4f3c|000102030405060708090a0b0c0d0e0f',
    defaultInput: `0|${'0'.repeat(32)}`,
    securityStatus: 'secure',
    keyPlaceholder: 'dataKeyHex|tweakKeyHex (must be different keys)',
  },
  {
    id: "aes",
    name: "AES",
    category: "symmetric",
    description:
      "Advanced Encryption Standard. A highly secure, standard block cipher supporting key sizes of 128, 192, or 256 bits.",
    defaultKey: "000102030405060708090a0b0c0d0e0f",
    defaultInput: "00112233445566778899aabbccddeeff",
    securityStatus: "secure",
    keyPlaceholder: "32/48/64-character hex key",
    options: [
      {
        name: "Hex Input Mode",
        id: "hexInput",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "camellia",
    name: "Camellia",
    category: "symmetric",
    description:
      "A symmetric key block cipher jointly developed by Mitsubishi Electric and NTT, widely used and standardized (RFC 3713).",
    defaultKey: "0123456789abcdeffedcba9876543210",
    defaultInput: "0123456789abcdeffedcba9876543210",
    securityStatus: "secure",
    keyPlaceholder: "32/48/64-character hex key (128/192/256-bit)",
    options: [
      {
        name: "Mode of Operation",
        id: "mode",
        type: "select",
        default: "ECB",
        choices: [
          { label: "ECB (Electronic Codebook)", value: "ECB" },
          { label: "CBC (Cipher Block Chaining)", value: "CBC" },
        ],
      },
      {
        name: "Padding",
        id: "padding",
        type: "boolean",
        default: true,
      },
      {
        name: "Hex Input Mode",
        id: "hexInput",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: 'serpent',
    name: 'Serpent',
    category: 'symmetric',
    description: 'An AES finalist (1998, runner-up to Rijndael) with the largest security margin of the finalists — 32 rounds using 8 different S-boxes cycled per round, versus AES\'s single S-box.',
    defaultKey: '000102030405060708090a0b0c0d0e0f',
    defaultInput: '00112233445566778899aabbccddeeff',
    securityStatus: 'secure',
    keyPlaceholder: '32-character hex key (128-bit)',
  },
  {
    id: 'chacha20-poly1305',
    name: 'ChaCha20-Poly1305',
    category: 'symmetric',
    description: 'RFC 8439 AEAD combining the existing ChaCha20 and Poly1305 modules — the software-oriented alternative to AES-GCM, used by TLS 1.3 and WireGuard when hardware AES acceleration isn\'t available.',
    defaultKey: '808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e|070000004041424344454647',
    defaultInput: '4c6164696573',
    securityStatus: 'secure',
    keyPlaceholder: 'keyHex(32B)|nonceHex(12B)|aadHex(optional)',
  },
  {
    id: 'speck',
    name: 'Speck128/128',
    category: 'symmetric',
    description: 'An NSA lightweight ARX cipher (2013) using only addition, rotation, and XOR — no S-boxes or lookup tables at all, unlike every other symmetric cipher in this registry.',
    defaultKey: '0f0e0d0c0b0a09080706050403020100',
    defaultInput: '6f6e6920736968746d2073696874706d',
    securityStatus: 'secure',
    keyPlaceholder: '32-character hex key (128-bit)',
  },
  {
    id: 'aes-ccm',
    name: 'AES-CCM',
    category: 'symmetric',
    description: 'Counter with CBC-MAC (NIST SP 800-38C) — an authenticated mode composed from AES, contrasted with AES-GCM: authentication here is literal CBC-MAC re-running the block cipher, not GHASH polynomial evaluation.',
    defaultKey: '2b7e151628aed2a6abf7158809cf4f3c|000102030405060708090a0b',
    defaultInput: '48656c6c6f2c20574f524c4421',
    securityStatus: 'secure',
    keyPlaceholder: 'keyHex|nonceHex(12 bytes)|aadHex(optional)',
  },
  {
    id: 'threefish',
    name: 'Threefish-256',
    category: 'symmetric',
    description: 'A tweakable, large-block ARX cipher (2008) underlying the Skein hash function (a SHA-3 finalist). 256-bit block, 72 rounds, and a 128-bit tweak that varies ciphertext without changing the key — no other cipher here exposes a tweak input.',
    defaultKey: '17161514131211101f1e1d1c1b1a191827262524232221202f2e2d2c2b2a2928|07060504030201000f0e0d0c0b0a0908',
    defaultInput: '0'.repeat(64),
    securityStatus: 'secure',
    keyPlaceholder: '64-char hex key, optionally "|32-char hex tweak"',
  },
  {
    id: 'xchacha20',
    name: 'XChaCha20',
    category: 'symmetric',
    description: 'The 192-bit-nonce extension of ChaCha20 (used by libsodium) — an HChaCha20 subkey-derivation step, the ChaCha20 sibling of this batch\'s XSalsa20, lets you pick nonces randomly instead of managing a counter.',
    defaultKey: '808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e|404142434445464748494a4b4c4d4e4f5051525354555657',
    defaultInput: '4c6164696573',
    securityStatus: 'secure',
    keyPlaceholder: 'keyHex(32B)|nonceHex(24B)',
  },
  {
    id: 'gost',
    name: 'GOST 28147-89',
    category: 'symmetric',
    description: 'The Soviet/Russian government standard block cipher (declassified 1994) — 256-bit key, 32-round Feistel. Uniquely, the S-boxes are a negotiated parameter, not fixed by the standard; this demo uses a published reference set.',
    defaultKey: '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f',
    defaultInput: '0000000000000000',
    securityStatus: 'secure',
    keyPlaceholder: '64-character hex key (256-bit)',
  },
  {
    id: 'xsalsa20',
    name: 'XSalsa20',
    category: 'symmetric',
    description: 'The 192-bit-nonce extension of Salsa20 (used by NaCl/libsodium) — an HSalsa20 subkey-derivation step lets you pick nonces randomly instead of managing a counter.',
    defaultKey: '1b27556473e985d462cd51197a9a46c76009549eac6474f206c4ee0844f6838|69696ee955b62b73cd62bda875fc73d68219e0036b7a0b37',
    defaultInput: '4c6164696573',
    securityStatus: 'secure',
    keyPlaceholder: 'keyHex(32B)|nonceHex(24B)',
  },
  {
    id: "sha256",
    name: "SHA-256",
    category: "hash",
    description:
      "Secure Hash Algorithm 2. Produces a unique 256-bit hash output representing the input message.",
    defaultKey: "",
    defaultInput: "abc",
    securityStatus: "secure",
  },
  {
    id: "sha512",
    name: "SHA-512",
    category: "hash",
    description:
      "Secure Hash Algorithm 2 with 64-bit words, producing a secure 512-bit digest.",
    defaultKey: "",
    defaultInput: "abc",
    securityStatus: "secure",
  },
  {
    id: "sm3",
    name: "SM3 Hash",
    category: "hash",
    description:
      "Chinese National Standard cryptographic hash function (GB/T 32905-2016). Produces a 256-bit message digest using 64 ARX compression rounds.",
    defaultKey: "",
    defaultInput: "abc",
    securityStatus: "secure",
  },
  {
    id: "md5",
    name: "MD5",
    category: "hash",
    description:
      "A widely used legacy hash producing a 128-bit output. Cryptographically broken due to collision vulnerabilities.",
    defaultKey: "",
    defaultInput: "abc",
    securityStatus: "broken",
  },
  {
    id: "hmac",
    name: "HMAC-SHA256",
    category: "hash",
    description:
      "Keyed-hash Message Authentication Code. Combines SHA-256 with a cryptographic secret key.",
    defaultKey: "Jefe",
    defaultInput: "what do ya want for nothing?",
    securityStatus: "secure",
    keyPlaceholder: "HMAC Secret Key",
  },
  {
    id: 'cmac',
    name: 'AES-CMAC',
    category: 'hash',
    description: 'A MAC built entirely from AES block-cipher calls plus a GF(2^128) subkey-derivation step (NIST SP 800-38B) — no separate hash function, unlike HMAC. Composed from the existing AES module, no new dependencies.',
    defaultKey: '2b7e151628aed2a6abf7158809cf4f3c',
    defaultInput: '6bc1bee22e409f96e93d7e117393172a',
    securityStatus: 'secure',
  },
  {
    id: "bcrypt",
    name: "Bcrypt",
    category: "hash",
    description:
      "A password hashing function incorporating a salt and cost factor, designed to be slow to prevent brute force.",
    defaultKey: "password",
    defaultInput: "password",
    securityStatus: "secure",
    options: [
      {
        name: "Rounds (Cost)",
        id: "rounds",
        type: "number",
        default: 4,
      },
    ],
  },
  {
    id: "xxhash",
    name: "XXHash32",
    category: "hash",
    description:
      "A very fast non-cryptographic 32-bit hash used for checksums, hash tables, and data integrity demos.",
    defaultKey: "0",
    defaultInput: "Hello, World!",
    securityStatus: "deprecated",
    keyPlaceholder: "Unsigned 32-bit seed (e.g. 0 or 0x1)",
    options: [
      {
        name: "Input Encoding",
        id: "encoding",
        type: "select",
        default: "utf8",
        choices: [
          { label: "UTF-8 text", value: "utf8" },
          { label: "Hex bytes", value: "hex" },
          { label: "Base64", value: "base64" },
          { label: "Binary bytes", value: "binary" },
        ],
      },
    ],
  },
  {
    id: 'bloom-filter',
    name: 'Bloom Filter Simulator',
    category: 'hash',
    description: 'A space-efficient probabilistic data structure testing set membership with zero false negatives and a tunable false-positive probability.',
    defaultKey: '3',
    defaultInput: 'phishing-bank-login.com',
    securityStatus: 'secure',
    keyPlaceholder: 'Number of hash functions k (e.g. 3)',
    options: [
      {
        name: 'Bit Array Size (m)',
        id: 'size',
        type: 'number',
        default: 64,
      },
      {
        name: 'Hash Functions (k)',
        id: 'numHashes',
        type: 'number',
        default: 3,
      },
    ],
  },
  {
    id: 'hkdf',
    name: 'HKDF (HMAC Key Derivation)',
    category: 'hash',
    description: 'HMAC-based Extract-and-Expand Key Derivation Function (RFC 5869) that converts weak or shared input keying material into cryptographically strong output keys.',
    defaultKey: '000102030405060708090a0b0c',
    defaultInput: '0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b',
    securityStatus: 'secure',
    keyPlaceholder: 'Salt hex or text (optional)',
    options: [
      {
        name: 'Hash Function',
        id: 'hash',
        type: 'select',
        default: 'SHA-256',
        choices: [
          { label: 'SHA-256 (32-byte HashLen)', value: 'SHA-256' },
          { label: 'SHA-512 (64-byte HashLen)', value: 'SHA-512' },
          { label: 'SHA-1 (20-byte HashLen)', value: 'SHA-1' },
        ],
      },
      {
        name: 'Context Info (info)',
        id: 'info',
        type: 'text',
        default: 'f0f1f2f3f4f5f6f7f8f9',
      },
      {
        name: 'Derived Key Length (L bytes)',
        id: 'keyLength',
        type: 'number',
        default: 42,
      },
    ],
  },
  {
    id: 'blake2s',
    name: 'BLAKE2s',
    category: 'hash',
    description: 'The 32-bit-word sibling of BLAKE2b (2012), optimized for 8- to 32-bit platforms — smaller blocks, fewer rounds, 256-bit max output. Used internally by Argon2.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'secure',
  },
  {
    id: 'sha224',
    name: 'SHA-224',
    category: 'hash',
    description: 'A truncated SHA-2 family member (FIPS 180-4) with its OWN initial hash value — not simply SHA-256\'s output cut short, which is a deliberate design choice to prevent leaking one digest from the other.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'secure',
  },
  {
    id: 'sha384',
    name: 'SHA-384',
    category: 'hash',
    description: 'The 384-bit truncated member of the SHA-512 family (FIPS 180-4), with its own distinct initial hash value, same design principle as SHA-224 relative to SHA-256.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'secure',
  },
  {
    id: 'shake128',
    name: 'SHAKE128',
    category: 'hash',
    description: 'An extendable-output function (XOF, NIST FIPS 202) — unlike every other hash here, output length is a parameter you choose, not fixed. Same Keccak permutation family as SHA-3.',
    defaultKey: '32',
    defaultInput: 'abc',
    securityStatus: 'secure',
    keyPlaceholder: 'requested output length in bytes (default 32)',
  },
  {
    id: 'shake256',
    name: 'SHAKE256',
    category: 'hash',
    description: 'The wider-capacity sibling of SHAKE128 (NIST FIPS 202) — same extendable-output design, larger security margin.',
    defaultKey: '32',
    defaultInput: 'abc',
    securityStatus: 'secure',
    keyPlaceholder: 'requested output length in bytes (default 32)',
  },
  {
    id: 'md4',
    name: 'MD4',
    category: 'hash',
    description: 'The direct predecessor to MD5 (1990) — fully broken today. Simpler than MD5: only 3 rounds (vs MD5\'s 4) and no additive per-step constants, illustrating exactly what MD5 was designed to fix.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'broken',
  },
  // Asymmetric
  {
    id: "rsa",
    name: "RSA-2048",
    category: "asymmetric",
    description:
      "An asymmetric cipher based on the difficulty of factoring large semiprimes. Supports key generation, encryption, and decryption.",
    defaultKey: "61,53,17",
    defaultInput: "HELLO",
    securityStatus: "secure",
    keyPlaceholder:
      "Enter: 3 values (p,q,e) or 2 values (n,e / n,d) if you already have n",
    options: [
      {
        name: "Demo Mode (Small Primes)",
        id: "demoMode",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: 'dsa',
    name: 'DSA',
    category: 'asymmetric',
    description: 'The finite-field discrete-log ancestor of ECDSA (NIST FIPS 186, 1994) — same r/s signature equation, computed in a prime-order subgroup instead of on a curve. Demo uses toy parameters; real DSA needs p>=2048 bits, q>=224 bits.',
    defaultKey: '47,23,4,5',
    defaultInput: '15',
    securityStatus: 'secure',
    keyPlaceholder: 'p,q,g,x (private, sign) or p,q,g,y (public, verify)',
  },
  {
    id: "dh",
    name: "Diffie-Hellman",
    category: "asymmetric",
    description:
      "A key exchange protocol enabling two parties to establish a shared secret over an insecure channel.",
    defaultKey: "23,5",
    defaultInput: "6,15",
    securityStatus: "secure",
    keyPlaceholder: "p,g parameters (e.g. 23,5)",
    options: [
      {
        name: "Bob Secret input (demo)",
        id: "bobSecret",
        type: "text",
        default: "15",
      },
    ],
  },
  {
    id: 'x448',
    name: 'X448',
    category: 'asymmetric',
    description: 'Diffie-Hellman key exchange over Curve448 (RFC 7748) — the higher-security sibling of X25519, targeting ~224-bit security with 56-byte keys instead of X25519\'s 32-byte keys.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'secure',
    keyPlaceholder: '56-byte private key hex (112 chars), or leave blank to generate one',
  },
  {
    id: "ecc",
    name: "ECC (ECDSA P-256)",
    category: "asymmetric",
    description:
      "Elliptic Curve Cryptography. Implements ECDSA signing and verification over the NIST P-256 curve.",
    defaultKey:
      "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
    defaultInput: "hello",
    securityStatus: "secure",
    keyPlaceholder: "32-byte private key hex (64 chars)",
  },
  {
    id: 'schnorr',
    name: 'Schnorr (BIP340)',
    category: 'asymmetric',
    description: 'Schnorr signatures per BIP340 over secp256k1, using x-only public keys. Provably secure under a simpler assumption than ECDSA and supports clean signature aggregation (MuSig) — compare against ecdsa.ts on the same curve.',
    defaultKey: '',
    defaultInput: 'hello',
    securityStatus: 'secure',
    keyPlaceholder: '32-byte private key hex (64 chars), or leave blank to generate one',
  },
  {
    id: 'elgamal-signature',
    name: 'ElGamal Signature',
    category: 'asymmetric',
    description: 'The ElGamal signature scheme (1985) — distinct from ElGamal encryption already in this registry. Historically the direct ancestor of DSA: DSA is this scheme computed in a smaller prime-order subgroup for shorter signatures.',
    defaultKey: '467,2,127',
    defaultInput: '100',
    securityStatus: 'secure',
    keyPlaceholder: 'p,g,x (private, sign) or p,g,y (public, verify)',
  },
  {
    id: 'ecies',
    name: 'ECIES (X25519)',
    category: 'asymmetric',
    description: 'Hybrid encryption: ephemeral X25519 key agreement + HKDF + AEAD, letting a sender encrypt an arbitrary-length message directly to a recipient\'s public key — no other asymmetric module here does this end-to-end.',
    defaultKey: '',
    defaultInput: 'A secret message for the recipient',
    securityStatus: 'secure',
    keyPlaceholder: 'recipient X25519 public key (encrypt) or your private key (decrypt)',
  },
  {
    id: 'ed448',
    name: 'Ed448',
    category: 'asymmetric',
    description: 'EdDSA signatures over Curve448 (RFC 8032) — the higher-security-margin sibling of Ed25519, using SHAKE256 internally instead of SHA-512. Completes the Curve25519/Curve448 x agreement/signing grid alongside x25519, x448, and ed25519.',
    defaultKey: '',
    defaultInput: 'hello',
    securityStatus: 'secure',
    keyPlaceholder: '57-byte private key hex (114 chars), or leave blank to generate one',
  },
];
