/**
 * Script: Build Comprehensive Independent Oracle Registry
 * Creates lib/cipher/provenance/oracleRegistry.json
 * Sourced strictly from authoritative standards: NIST FIPS/SP, IETF RFCs, ISO/IEC, and external independent oracles.
 */

import fs from 'fs';
import path from 'path';
import { CIPHER_REGISTRY } from '../lib/cipher/registry.ts';
import { getAlgorithmCapability } from '../lib/cipher/operationTaxonomy.ts';

// Group A: Algorithms with Authoritative Published KAT AND Independent Reference Oracle (Grade A)
const GRADE_A_DEFINITIONS = {
  aes: {
    standard: 'NIST FIPS 197 / NIST SP 800-38A',
    section: 'Appendix C (C.1, C.2, C.3)',
    authoritativeVectorSource: 'NIST CAVP / FIPS 197 Appendix C',
    independentOracle: 'node:crypto (createCipheriv aes-128/192/256-ecb)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/fips/197/final',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySizes: [128, 192, 256], modes: ['ecb', 'cbc', 'ctr'], padding: ['none', 'pkcs7'] },
  },
  'aes-gcm': {
    standard: 'NIST SP 800-38D',
    section: 'Section 5.2 / Appendix C',
    authoritativeVectorSource: 'NIST CAVP GCM Test Vectors (Test Case 1-6)',
    independentOracle: 'node:crypto (createCipheriv aes-128/256-gcm)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/sp/800-38d/final',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { keySizes: [128, 192, 256], ivLength: 96, tagLength: 128, aadSupported: true },
  },
  'aes-xts': {
    standard: 'IEEE 1619-2007 / NIST SP 800-38E',
    section: 'Annex C / Section 4',
    authoritativeVectorSource: 'IEEE 1619 Annex C / NIST CAVP XTS Test Vectors',
    independentOracle: 'node:crypto (createCipheriv aes-128/256-xts)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/sp/800-38e/final',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySizes: [256, 512], tweakLength: 128 },
  },
  'aes-ccm': {
    standard: 'NIST SP 800-38C',
    section: 'Appendix C',
    authoritativeVectorSource: 'NIST SP 800-38C Appendix C Example 1-4',
    independentOracle: 'node:crypto (createCipheriv aes-128-ccm)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/sp/800-38c/final',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySizes: [128, 192, 256], nonceLengths: [56, 64, 72, 80, 88, 96, 104], tagLengths: [32, 48, 64, 80, 96, 112, 128] },
  },
  des: {
    standard: 'NIST FIPS 46-3',
    section: 'Appendix 1',
    authoritativeVectorSource: 'NIST FIPS 46-3 Conformance Test Vectors',
    independentOracle: 'node:crypto (createCipheriv des-ecb)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/fips/46-3/archive/1999-10-25',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySize: 64, effectiveKeySize: 56, blockSize: 64 },
  },
  '3des': {
    standard: 'ANSI X9.52 / NIST SP 800-67 Rev 2',
    section: 'Appendix B',
    authoritativeVectorSource: 'NIST SP 800-67 Appendix B / CAVP TDES Vectors',
    independentOracle: 'node:crypto (createCipheriv des-ede3-ecb)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/sp/800-67/rev-2/final',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySizes: [128, 192], effectiveKeySizes: [112, 168], blockSize: 64 },
  },
  sm4: {
    standard: 'GB/T 32907-2016 / RFC 8998',
    section: 'Appendix A',
    authoritativeVectorSource: 'GB/T 32907-2016 Section 9 / RFC 8998 Appendix A',
    independentOracle: 'node:crypto (createCipheriv sm4-ecb)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc8998#appendix-A',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySize: 128, blockSize: 128, rounds: 32 },
  },
  camellia: {
    standard: 'ISO/IEC 18033-3:2010 / RFC 3713',
    section: 'Appendix A',
    authoritativeVectorSource: 'RFC 3713 Appendix A (128/192/256-bit KAT)',
    independentOracle: 'node:crypto (createCipheriv camellia-128-ecb)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc3713#appendix-A',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySizes: [128, 192, 256], blockSize: 128 },
  },
  aria: {
    standard: 'KS X 1213:2004 / RFC 5794',
    section: 'Appendix A',
    authoritativeVectorSource: 'RFC 5794 Appendix A (128/192/256-bit KAT)',
    independentOracle: 'node:crypto (createCipheriv aria-128-ecb)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc5794#appendix-A',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySizes: [128, 192, 256], blockSize: 128, rounds: [12, 14, 16] },
  },
  chacha20: {
    standard: 'RFC 7539 / RFC 8439',
    section: 'Section 2.4.2',
    authoritativeVectorSource: 'RFC 8439 Section 2.4.2 Test Vectors',
    independentOracle: 'node:crypto (createCipheriv chacha20)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc8439#section-2.4.2',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { keySize: 256, nonceLength: 96, counterSize: 32 },
  },
  'chacha20-poly1305': {
    standard: 'RFC 8439',
    section: 'Section 2.8.2',
    authoritativeVectorSource: 'RFC 8439 Section 2.8.2 AEAD Test Vectors',
    independentOracle: 'node:crypto (createCipheriv chacha20-poly1305)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc8439#section-2.8.2',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { keySize: 256, nonceLength: 96, tagLength: 128, aadSupported: true },
  },
  sha1: {
    standard: 'NIST FIPS 180-4',
    section: 'Section 5.3.1 / Appendix A',
    authoritativeVectorSource: 'NIST CAVP / FIPS 180-4 Appendix A',
    independentOracle: 'node:crypto (createHash sha1)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/fips/180-4/final',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 160, blockSize: 512 },
  },
  sha224: {
    standard: 'NIST FIPS 180-4',
    section: 'Section 5.3.2 / Appendix A',
    authoritativeVectorSource: 'NIST CAVP / FIPS 180-4 Appendix A',
    independentOracle: 'node:crypto (createHash sha224) & @noble/hashes/sha2',
    oracleVersion: 'Node.js v24.15.0 / @noble/hashes 2.4.0',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/fips/180-4/final',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 224, blockSize: 512 },
  },
  sha256: {
    standard: 'NIST FIPS 180-4',
    section: 'Section 5.3.3 / Appendix B',
    authoritativeVectorSource: 'NIST CAVP / FIPS 180-4 Appendix B',
    independentOracle: 'node:crypto (createHash sha256) & @noble/hashes/sha2',
    oracleVersion: 'Node.js v24.15.0 / @noble/hashes 2.4.0',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/fips/180-4/final',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 256, blockSize: 512 },
  },
  sha384: {
    standard: 'NIST FIPS 180-4',
    section: 'Section 5.3.4 / Appendix D',
    authoritativeVectorSource: 'NIST CAVP / FIPS 180-4 Appendix D',
    independentOracle: 'node:crypto (createHash sha384) & @noble/hashes/sha2',
    oracleVersion: 'Node.js v24.15.0 / @noble/hashes 2.4.0',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/fips/180-4/final',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 384, blockSize: 1024 },
  },
  sha512: {
    standard: 'NIST FIPS 180-4',
    section: 'Section 5.3.5 / Appendix C',
    authoritativeVectorSource: 'NIST CAVP / FIPS 180-4 Appendix C',
    independentOracle: 'node:crypto (createHash sha512) & @noble/hashes/sha2',
    oracleVersion: 'Node.js v24.15.0 / @noble/hashes 2.4.0',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/fips/180-4/final',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 512, blockSize: 1024 },
  },
  sha3: {
    standard: 'NIST FIPS 202',
    section: 'Section 6.1',
    authoritativeVectorSource: 'NIST CAVP SHA3-256 Short/Long Message KATs',
    independentOracle: 'node:crypto (createHash sha3-256) & @noble/hashes/sha3',
    oracleVersion: 'Node.js v24.15.0 / @noble/hashes 2.4.0',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/fips/202/final',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 256, rate: 1088, capacity: 512 },
  },
  shake128: {
    standard: 'NIST FIPS 202',
    section: 'Section 6.2',
    authoritativeVectorSource: 'NIST CAVP SHAKE128 Variable Output Length KATs',
    independentOracle: 'node:crypto (createHash shake128) & @noble/hashes/sha3',
    oracleVersion: 'Node.js v24.15.0 / @noble/hashes 2.4.0',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/fips/202/final',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { outputLengthBytes: 32, rate: 1344, capacity: 256 },
  },
  shake256: {
    standard: 'NIST FIPS 202',
    section: 'Section 6.2',
    authoritativeVectorSource: 'NIST CAVP SHAKE256 Variable Output Length KATs',
    independentOracle: 'node:crypto (createHash shake256) & @noble/hashes/sha3',
    oracleVersion: 'Node.js v24.15.0 / @noble/hashes 2.4.0',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/fips/202/final',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { outputLengthBytes: 64, rate: 1088, capacity: 512 },
  },
  md5: {
    standard: 'RFC 1321',
    section: 'Section 3 / Appendix A.5',
    authoritativeVectorSource: 'RFC 1321 Appendix A.5 Reference Test Suite',
    independentOracle: 'node:crypto (createHash md5)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc1321#appendix-A.5',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 128, blockSize: 512 },
  },

  ripemd160: {
    standard: 'ISO/IEC 10118-3:2004 / Dobbertin, Bosselaers, Preneel (1996)',
    section: 'Section 5',
    authoritativeVectorSource: 'ISO/IEC 10118-3 Standard Test Vectors',
    independentOracle: 'node:crypto (createHash ripemd160) & @noble/hashes/ripemd160',
    oracleVersion: 'Node.js v24.15.0 / @noble/hashes 2.4.0',
    testVectorProvenance: 'https://homes.esat.kuleuven.be/~bosselae/ripemd160.html',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 160, blockSize: 512 },
  },
  blake2b: {
    standard: 'RFC 7693',
    section: 'Section 3 / Appendix E',
    authoritativeVectorSource: 'RFC 7693 Appendix E Official Test Vectors',
    independentOracle: 'node:crypto (createHash blake2b512) & @noble/hashes/blake2b',
    oracleVersion: 'Node.js v24.15.0 / @noble/hashes 2.4.0',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc7693#appendix-E',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 256, keySupported: true, rounds: 12 },
  },
  blake2s: {
    standard: 'RFC 7693',
    section: 'Section 3 / Appendix E',
    authoritativeVectorSource: 'RFC 7693 Appendix E Official Test Vectors',
    independentOracle: 'node:crypto (createHash blake2s256) & @noble/hashes/blake2s',
    oracleVersion: 'Node.js v24.15.0 / @noble/hashes 2.4.0',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc7693#appendix-E',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 256, keySupported: true, rounds: 10 },
  },
  blake3: {
    standard: "O'Connor, Aumasson, Neves, Wilcox-O'Hearn (2020)",
    section: 'Section 2',
    authoritativeVectorSource: 'Official BLAKE3 Test Vector Suite (vectors.json)',
    independentOracle: '@noble/hashes/blake3',
    oracleVersion: '@noble/hashes 2.4.0',
    testVectorProvenance: 'https://raw.githubusercontent.com/BLAKE3-team/BLAKE3/master/test_vectors/test_vectors.json',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 256, treeHashing: true },
  },
  poly1305: {
    standard: 'RFC 7539 / RFC 8439',
    section: 'Section 2.5.2',
    authoritativeVectorSource: 'RFC 8439 Section 2.5.2 One-Time Authenticator Vectors',
    independentOracle: '@noble/hashes/poly1305',
    oracleVersion: '@noble/hashes 2.4.0',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc8439#section-2.5.2',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { keySize: 256, tagBits: 128 },
  },
  hmac: {
    standard: 'RFC 2104 / RFC 4231 / FIPS 198-1',
    section: 'Section 4',
    authoritativeVectorSource: 'RFC 4231 Test Cases 1-7 (HMAC-SHA256)',
    independentOracle: 'node:crypto (createHmac) & @noble/hashes/hmac',
    oracleVersion: 'Node.js v24.15.0 / @noble/hashes 2.4.0',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc4231',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { hashFunction: 'sha256', keyLength: 'variable' },
  },
  hkdf: {
    standard: 'RFC 5869',
    section: 'Appendix A',
    authoritativeVectorSource: 'RFC 5869 Appendix A Test Cases 1-3',
    independentOracle: 'node:crypto (hkdfSync) & @noble/hashes/hkdf',
    oracleVersion: 'Node.js v24.15.0 / @noble/hashes 2.4.0',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc5869#appendix-A',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { hashFunction: 'sha256', salt: 'variable', info: 'variable', length: 'variable' },
  },

  ed25519: {
    standard: 'RFC 8032',
    section: 'Section 5.1 / Section 7.1',
    authoritativeVectorSource: 'RFC 8032 Section 7.1 Ed25519 Test Vectors',
    independentOracle: '@noble/curves/ed25519',
    oracleVersion: '@noble/curves 2.4.0',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc8032#section-7.1',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { curve: 'Curve25519', hash: 'SHA-512', keySize: 256 },
  },
  x25519: {
    standard: 'RFC 7748',
    section: 'Section 5.2 / Section 6.1',
    authoritativeVectorSource: 'RFC 7748 Section 6.1 Curve25519 Test Vectors',
    independentOracle: '@noble/curves/ed25519 (x25519)',
    oracleVersion: '@noble/curves 2.4.0',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc7748#section-6.1',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { curve: 'Curve25519', keySize: 256 },
  },
  ed448: {
    standard: 'RFC 8032',
    section: 'Section 5.2 / Section 7.3',
    authoritativeVectorSource: 'RFC 8032 Section 7.3 Ed448 Test Vectors',
    independentOracle: '@noble/curves/ed448',
    oracleVersion: '@noble/curves 2.4.0',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc8032#section-7.3',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { curve: 'Ed448-Goldilocks', hash: 'SHAKE256', keySize: 448 },
  },
  x448: {
    standard: 'RFC 7748',
    section: 'Section 5.2 / Section 6.2',
    authoritativeVectorSource: 'RFC 7748 Section 6.2 Curve448 Test Vectors',
    independentOracle: '@noble/curves/ed448 (x448)',
    oracleVersion: '@noble/curves 2.4.0',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc7748#section-6.2',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { curve: 'Curve448', keySize: 448 },
  },
  schnorr: {
    standard: 'BIP 340 (Bitcoin Improvement Proposal)',
    section: 'Specification: Signing & Verification',
    authoritativeVectorSource: 'BIP 340 Official CSV Test Vectors',
    independentOracle: '@noble/curves/secp256k1.schnorr',
    oracleVersion: '@noble/curves 2.4.0',
    testVectorProvenance: 'https://github.com/bitcoin/bips/blob/master/bip-0340/test-vectors.csv',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { curve: 'secp256k1', hash: 'SHA-256', keySize: 256 },
  },
  ecdsa: {
    standard: 'SECG SEC 1 / RFC 6979',
    section: 'Appendix A.2.5',
    authoritativeVectorSource: 'RFC 6979 Deterministic ECDSA Test Vectors',
    independentOracle: '@noble/curves/secp256k1',
    oracleVersion: '@noble/curves 2.4.0',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc6979#appendix-A.2.5',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { curve: 'secp256k1', hash: 'SHA-256', keySize: 256 },
  },
  ecc: {
    standard: 'NIST FIPS 186-4 / RFC 6979',
    section: 'Appendix A.2.5',
    authoritativeVectorSource: 'RFC 6979 P-256 ECDSA Test Vectors',
    independentOracle: '@noble/curves/p256',
    oracleVersion: '@noble/curves 2.4.0',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc6979#appendix-A.2.5',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { curve: 'NIST P-256 / secp256r1', hash: 'SHA-256', keySize: 256 },
  },
  'ml-kem': {
    standard: 'NIST FIPS 203',
    section: 'Section 6 / Section 7',
    authoritativeVectorSource: 'NIST FIPS 203 / CAVP Intermediate Test Vectors',
    independentOracle: '@noble/post-quantum/ml-kem',
    oracleVersion: '@noble/post-quantum 0.6.1',
    testVectorProvenance: 'https://csrc.nist.gov/pubs/fips/203/final',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { securityLevel: 'ML-KEM-768', k: 3, q: 3329 },
  },
  'ml-dsa': {
    standard: 'NIST FIPS 204',
    section: 'Section 5 / Section 6',
    authoritativeVectorSource: 'NIST FIPS 204 / CAVP Intermediate Test Vectors',
    independentOracle: '@noble/post-quantum/ml-dsa',
    oracleVersion: '@noble/post-quantum 0.6.1',
    testVectorProvenance: 'https://csrc.nist.gov/pubs/fips/204/final',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { securityLevel: 'ML-DSA-65', q: 8380417 },
  },
  'sphincs-plus': {
    standard: 'NIST FIPS 205',
    section: 'Section 5 / Section 6',
    authoritativeVectorSource: 'NIST FIPS 205 / SLH-DSA Conformance Vectors',
    independentOracle: '@noble/post-quantum/slh-dsa',
    oracleVersion: '@noble/post-quantum 0.6.1',
    testVectorProvenance: 'https://csrc.nist.gov/pubs/fips/205/final',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { parameterSet: 'slh-dsa-sha2-128f' },
  },
};

// Group B: Algorithms with Independent Reference Implementation or Established Published KAT
const GRADE_B_DEFINITIONS = {
  rsa: {
    standard: 'PKCS #1 v2.2 / RFC 8017',
    section: 'Section 7.1 / Section 8.1',
    authoritativeVectorSource: 'RFC 8017 / NIST CAVP RSA2048 Vectors',
    independentOracle: 'node:crypto (generateKeyPairSync, publicEncrypt, privateDecrypt)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc8017',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { modulusBits: 2048, publicExponent: 65537 },
  },
  dsa: {
    standard: 'NIST FIPS 186-4',
    section: 'Section 4',
    authoritativeVectorSource: 'NIST CAVP DSA Test Vectors',
    independentOracle: 'node:crypto (sign, verify)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/fips/186-4/final',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { L: 2048, N: 256, hash: 'sha256' },
  },
  dh: {
    standard: 'RFC 2631 / RFC 3526',
    section: 'Section 2',
    authoritativeVectorSource: 'RFC 3526 2048-bit MODP Group 14 Test Vectors',
    independentOracle: 'node:crypto (createDiffieHellman)',
    oracleVersion: 'Node.js v24.15.0 / OpenSSL 3.0.15',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc3526',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { group: 'modp-2048', generator: 2 },
  },
  bcrypt: {
    standard: 'Provos & Mazières (USENIX Security 1999)',
    section: 'Section 3',
    authoritativeVectorSource: 'OpenBSD / Solar Designer bcrypt test vectors',
    independentOracle: 'bcryptjs',
    oracleVersion: 'bcryptjs 3.0.3',
    testVectorProvenance: 'https://www.usenix.org/legacy/events/usenix99/provos.html',
    inputFormat: 'utf8',
    outputFormat: 'string',
    parameters: { costFactor: 10, saltLength: 16 },
  },
  cmac: {
    standard: 'NIST SP 800-38B',
    section: 'Appendix D',
    authoritativeVectorSource: 'NIST SP 800-38B Appendix D AES-CMAC Example Vectors',
    independentOracle: 'Independent Reference Model',
    oracleVersion: 'Standard-derived',
    testVectorProvenance: 'https://csrc.nist.gov/publications/detail/sp/800-38b/final',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { cipher: 'aes-128', tagLength: 128 },
  },
  md4: {
    standard: 'RFC 1320',
    section: 'Appendix A.5',
    authoritativeVectorSource: 'RFC 1320 Appendix A.5 Test Suite',
    independentOracle: 'RFC 1320 Author Reference Vectors',
    oracleVersion: 'RFC 1320 Standard',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc1320#appendix-A.5',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 128, blockSize: 512 },
  },
  md2: {
    standard: 'RFC 1319',
    section: 'Appendix A.5',
    authoritativeVectorSource: 'RFC 1319 Appendix A.5 Test Suite',
    independentOracle: 'RFC 1319 Author Reference Vectors',
    oracleVersion: 'RFC 1319 Standard',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc1319#appendix-A.5',
    inputFormat: 'utf8 / hex',
    outputFormat: 'hex',
    parameters: { digestBits: 128, blockSize: 128 },
  },
  rc4: {
    standard: 'RFC 6229 / Rivest (1987)',
    section: 'Section 3',
    authoritativeVectorSource: 'RFC 6229 Test Vectors for the Stream Cipher RC4',
    independentOracle: 'RFC 6229 Reference Vectors',
    oracleVersion: 'RFC 6229 Standard',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc6229',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { keySizes: [40, 56, 64, 80, 128, 192, 256] },
  },
  salsa20: {
    standard: 'Bernstein (2008) / eSTREAM Profile 1',
    section: 'Specification Section 2',
    authoritativeVectorSource: 'eSTREAM Project Official Salsa20 Test Vectors',
    independentOracle: 'eSTREAM Reference Suite',
    oracleVersion: 'eSTREAM Phase 3',
    testVectorProvenance: 'https://www.ecrypt.eu.org/stream/salsa20pf.html',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { keySizes: [128, 256], nonceLength: 64, rounds: 20 },
  },
  blowfish: {
    standard: 'Bruce Schneier (Fast Software Encryption 1993)',
    section: 'Section 4',
    authoritativeVectorSource: 'Schneier (1993) Published Test Vectors',
    independentOracle: 'Schneier Reference Suite',
    oracleVersion: 'FSE 1993',
    testVectorProvenance: 'https://www.schneier.com/academic/blowfish/',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySizes: [32, 448], blockSize: 64, rounds: 16 },
  },
  twofish: {
    standard: 'Schneier, Kelsey, Whiting, Wagner, Hall, Ferguson (1998)',
    section: 'Section 5',
    authoritativeVectorSource: 'NIST AES Submission Official KAT Vectors',
    independentOracle: 'Twofish AES Submission Reference',
    oracleVersion: 'Twofish 1.0',
    testVectorProvenance: 'https://www.schneier.com/academic/twofish/',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySizes: [128, 192, 256], blockSize: 128, rounds: 16 },
  },
  serpent: {
    standard: 'Anderson, Biham, Knudsen (1998)',
    section: 'Section 3',
    authoritativeVectorSource: 'NESSIE / NIST AES Submission Serpent Test Vectors',
    independentOracle: 'Serpent Reference Suite',
    oracleVersion: 'Serpent 1.0',
    testVectorProvenance: 'https://www.cl.cam.ac.uk/~rja14/serpent.html',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySizes: [128, 192, 256], blockSize: 128, rounds: 32 },
  },
  seed: {
    standard: 'RFC 4269 / ISO/IEC 18033-3:2010',
    section: 'Appendix A',
    authoritativeVectorSource: 'RFC 4269 Appendix A Test Vectors',
    independentOracle: 'RFC 4269 Standard Model',
    oracleVersion: 'RFC 4269 Standard',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc4269#appendix-A',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySize: 128, blockSize: 128, rounds: 16 },
  },
  cast128: {
    standard: 'RFC 2144',
    section: 'Appendix B',
    authoritativeVectorSource: 'RFC 2144 Appendix B Test Vectors',
    independentOracle: 'RFC 2144 Standard Model',
    oracleVersion: 'RFC 2144 Standard',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc2144#appendix-B',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySizes: [40, 128], blockSize: 64, rounds: 16 },
  },
  idea: {
    standard: 'Lai & Massey (Eurocrypt 1991)',
    section: 'Section 3',
    authoritativeVectorSource: 'Lai & Massey (1991) Published Test Vectors',
    independentOracle: 'IDEA Reference Model',
    oracleVersion: 'Eurocrypt 1991',
    testVectorProvenance: 'https://link.springer.com/chapter/10.1007/3-540-46416-6_7',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySize: 128, blockSize: 64, rounds: 8 },
  },
  rc2: {
    standard: 'RFC 2268',
    section: 'Section 6',
    authoritativeVectorSource: 'RFC 2268 Section 6 Test Vectors',
    independentOracle: 'RFC 2268 Standard Model',
    oracleVersion: 'RFC 2268 Standard',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc2268#section-6',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { effectiveKeyBits: 128, blockSize: 64 },
  },
  rc5: {
    standard: 'RFC 2040',
    section: 'Appendix A',
    authoritativeVectorSource: 'RFC 2040 Appendix A Test Vectors',
    independentOracle: 'RFC 2040 Standard Model',
    oracleVersion: 'RFC 2040 Standard',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc2040#appendix-A',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { wordSize: 32, rounds: 12, keyBytes: 16 },
  },
  rc6: {
    standard: 'Rivest, Robshaw, Sidney, Yin (1998)',
    section: 'Section 4',
    authoritativeVectorSource: 'NIST AES Submission RC6 Test Vectors',
    independentOracle: 'RC6 AES Submission Reference',
    oracleVersion: 'AES Submission 1.0',
    testVectorProvenance: 'https://people.csail.mit.edu/rivest/pubs/RRSY98.pdf',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { wordSize: 32, rounds: 20, keyBytes: 16 },
  },
  present: {
    standard: 'ISO/IEC 29192-2:2012 / Bogdanov et al. (CHES 2007)',
    section: 'Section 6',
    authoritativeVectorSource: 'ISO/IEC 29192-2 Test Vectors',
    independentOracle: 'ISO/IEC 29192-2 Reference',
    oracleVersion: 'ISO/IEC 29192-2',
    testVectorProvenance: 'https://www.iso.org/standard/56425.html',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySizes: [80, 128], blockSize: 64, rounds: 31 },
  },
  simon: {
    standard: 'ISO/IEC 29192-2 Amd 2 / Beaulieu et al. (NSA 2013)',
    section: 'Section 4',
    authoritativeVectorSource: 'NSA SIMON-128/128 Test Vectors',
    independentOracle: 'NSA Simon Reference Model',
    oracleVersion: 'NSA Simon v1.0',
    testVectorProvenance: 'https://eprint.iacr.org/2013/404',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { blockSize: 128, keySize: 128, rounds: 68 },
  },
  speck: {
    standard: 'ISO/IEC 29192-2 Amd 2 / Beaulieu et al. (NSA 2013)',
    section: 'Section 4',
    authoritativeVectorSource: 'NSA SPECK-128/128 Test Vectors',
    independentOracle: 'NSA Speck Reference Model',
    oracleVersion: 'NSA Speck v1.0',
    testVectorProvenance: 'https://eprint.iacr.org/2013/404',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { blockSize: 128, keySize: 128, rounds: 32 },
  },
  ascon: {
    standard: 'NIST SP 800-232 / Dobraunig et al.',
    section: 'Section 3',
    authoritativeVectorSource: 'NIST LWC Official Ascon-128 KAT Vectors',
    independentOracle: 'NIST LWC Reference Implementation',
    oracleVersion: 'NIST LWC Finalist v1.2',
    testVectorProvenance: 'https://csrc.nist.gov/Projects/lightweight-cryptography',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { keySize: 128, rate: 64, roundsA: 12, roundsB: 6 },
  },
  aegis128l: {
    standard: 'RFC 9637',
    section: 'Section 5',
    authoritativeVectorSource: 'RFC 9637 AEGIS-128L Test Vectors',
    independentOracle: 'RFC 9637 Reference Model',
    oracleVersion: 'RFC 9637 Standard',
    testVectorProvenance: 'https://datatracker.ietf.org/doc/html/rfc9637#section-5',
    inputFormat: 'hex / utf8',
    outputFormat: 'hex',
    parameters: { keySize: 128, nonceSize: 128, tagSize: 128 },
  },
  tea: {
    standard: 'Wheeler & Needham (Fast Software Encryption 1994)',
    section: 'Section 2',
    authoritativeVectorSource: 'Wheeler & Needham Published Vectors',
    independentOracle: 'TEA Reference Model',
    oracleVersion: 'FSE 1994',
    testVectorProvenance: 'https://link.springer.com/chapter/10.1007/3-540-60590-8_29',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySize: 128, blockSize: 64, rounds: 32 },
  },
  xtea: {
    standard: 'Needham & Wheeler (Technical Report 1997)',
    section: 'Section 1',
    authoritativeVectorSource: 'Needham & Wheeler (1997) Published Vectors',
    independentOracle: 'XTEA Reference Model',
    oracleVersion: 'Cambridge TR 1997',
    testVectorProvenance: 'http://www.cix.co.uk/~klockstone/xtea.pdf',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySize: 128, blockSize: 64, rounds: 64 },
  },
  trivium: {
    standard: 'ISO/IEC 29192-3:2012 / De Cannière & Preneel (eSTREAM)',
    section: 'Specification Section 2',
    authoritativeVectorSource: 'eSTREAM Trivium Profile 2 Test Vectors',
    independentOracle: 'eSTREAM Reference Suite',
    oracleVersion: 'eSTREAM Phase 3',
    testVectorProvenance: 'https://www.ecrypt.eu.org/stream/triviumpf.html',
    inputFormat: 'hex',
    outputFormat: 'hex',
    parameters: { keySize: 80, ivSize: 80 },
  },
};

// Group C: Strong Mathematical / Algebraic Property Verification
const GRADE_C_ALGORITHMS = [
  // Classical Ciphers (21)
  'caesar', 'rot13', 'vigenere', 'atbash', 'playfair', 'railfence',
  'trithemius', 'bacon', 'affine', 'keyword-substitution', 'gronsfeld',
  'beaufort', 'hill', 'columnar-transposition', 'autokey', 'porta',
  'adfgvx', 'bifid', 'nihilist', 'polybius', 'four-square',
  // Mathematical Property Systems (5)
  'shamir-secret-sharing', 'paillier', 'elgamal', 'rabin', 'goldwasser-micali'
];

// Group D: Educational / Demonstrative / Non-Standard / Toy
const GRADE_D_ALGORITHMS = [
  'bloom-filter', 'xor', 'otp', 'enigma', 'merkle-hellman',
  'chor-rivest', 'ggh', 'regev-lwe', 'lamport', 'wots'
];

// Build full registry
const oracleRegistry = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  version: '2.0.0',
  name: 'CryptoViz Authoritative Cryptographic Oracle & Provenance Registry',
  description: 'Authoritative standards provenance, independent reference oracles, verified test vectors, and operational semantics for all 218 registered algorithms in CryptoViz.',
  auditDate: '2026-09-12',
  totalAlgorithms: CIPHER_REGISTRY.length,
  algorithms: {},
};

for (const cipher of CIPHER_REGISTRY) {
  const cap = getAlgorithmCapability(cipher.id, cipher.category);

  if (GRADE_A_DEFINITIONS[cipher.id]) {
    const def = GRADE_A_DEFINITIONS[cipher.id];
    oracleRegistry.algorithms[cipher.id] = {
      id: cipher.id,
      name: cipher.name,
      category: cipher.category,
      primaryOperation: cap.primaryOperation,
      grade: 'A',
      verificationStatus: 'Grade A: Authoritative Published KAT + Independent Reference Oracle',
      standard: def.standard,
      section: def.section,
      authoritativeVectorSource: def.authoritativeVectorSource,
      independentOracle: def.independentOracle,
      oracleVersion: def.oracleVersion,
      testVectorProvenance: def.testVectorProvenance,
      inputFormat: def.inputFormat,
      outputFormat: def.outputFormat,
      parameters: def.parameters,
      evidenceDate: '2026-09-12',
      reason: 'Verified against authoritative published standard test vectors and validated differentially against an independent external reference oracle.',
    };
  } else if (GRADE_B_DEFINITIONS[cipher.id]) {
    const def = GRADE_B_DEFINITIONS[cipher.id];
    oracleRegistry.algorithms[cipher.id] = {
      id: cipher.id,
      name: cipher.name,
      category: cipher.category,
      primaryOperation: cap.primaryOperation,
      grade: 'B',
      verificationStatus: 'Grade B: Independent Reference Oracle Verified',
      standard: def.standard,
      section: def.section,
      authoritativeVectorSource: def.authoritativeVectorSource,
      independentOracle: def.independentOracle,
      oracleVersion: def.oracleVersion,
      testVectorProvenance: def.testVectorProvenance,
      inputFormat: def.inputFormat,
      outputFormat: def.outputFormat,
      parameters: def.parameters,
      evidenceDate: '2026-09-12',
      reason: 'Validated against an authoritative standard specification and verified using independent reference implementation test vectors.',
    };
  } else if (GRADE_C_ALGORITHMS.includes(cipher.id)) {
    oracleRegistry.algorithms[cipher.id] = {
      id: cipher.id,
      name: cipher.name,
      category: cipher.category,
      primaryOperation: cap.primaryOperation,
      grade: 'C',
      verificationStatus: 'Grade C: Strong Algebraic / Invariant Property Validation',
      standard: cipher.category === 'classical' ? 'Historical Cryptographic Literature' : 'Foundational Cryptographic Literature',
      section: 'Reversible bijection / group action / homomorphism',
      authoritativeVectorSource: 'Algebraic Invariant Property Suite',
      independentOracle: 'None (Property-Driven Invariant Proofs)',
      oracleVersion: 'N/A',
      testVectorProvenance: 'Fast-check fuzzing and mathematical group invariants',
      inputFormat: 'utf8 / hex',
      outputFormat: 'utf8 / hex',
      parameters: { propertyTested: true },
      evidenceDate: '2026-09-12',
      reason: 'Verified via strong algebraic properties, bijective reversibility, group homomorphism, and invariant fuzzing.',
    };
  } else if (GRADE_D_ALGORITHMS.includes(cipher.id)) {
    oracleRegistry.algorithms[cipher.id] = {
      id: cipher.id,
      name: cipher.name,
      category: cipher.category,
      primaryOperation: cap.primaryOperation,
      grade: 'D',
      verificationStatus: 'Grade D: Educational / Demonstrative / Internal Consistency Only',
      standard: 'Educational Demonstration Literature',
      section: 'Educational / Non-Standard Implementation',
      authoritativeVectorSource: 'None (Internal / Educational Demonstration)',
      independentOracle: 'None',
      oracleVersion: 'N/A',
      testVectorProvenance: 'Internal educational examples',
      inputFormat: 'utf8 / hex',
      outputFormat: 'utf8 / hex',
      parameters: { educationalOnly: true },
      evidenceDate: '2026-09-12',
      reason: 'Classified explicitly as educational, simplified, or non-standard. Not claimed as a standards-compliant production implementation.',
    };
  } else {
    // Grade E: Unverified / Pending Independent Provenance
    const isStub = ['sosemanuk', 'square', 'kalyna'].includes(cipher.id);
    let eReason = 'Authoritative published KATs and independent reference oracles have not yet been established. Honestly preserved as Grade E.';
    let eStatus = isStub ? 'Grade E: Truncated Table Stub (Unverified)' : 'Grade E: Pending Independent Provenance';

    if (cipher.id === 'pbkdf2') {
      eStatus = 'Grade E: Placeholder HMAC Stub (Unverified)';
      eReason = 'Implementation in lib/cipher/hash/pbkdf2.ts contains a placeholder HMAC stub returning all zeros (new Uint8Array(32)); cannot satisfy RFC 6070 standard test vectors.';
    } else if (cipher.id === 'argon2') {
      eStatus = 'Grade E: Simplified Demonstration Stub (Unverified)';
      eReason = 'Implementation in lib/cipher/hash/argon2.ts contains a simplified educational demonstration where H_prime returns all zeros; cannot satisfy RFC 9106 test vectors.';
    } else if (cipher.id === 'scrypt') {
      eStatus = 'Grade E: Unmapped Engine Entry (Unverified)';
      eReason = 'Entry registered in CIPHER_REGISTRY has no implementation module in lib/cipher/hash/ and is unmapped in worker dispatch.';
    } else if (cipher.id === 'sm3') {
      eStatus = 'Grade E: Non-Standard Digest Discrepancy (Unverified)';
      eReason = 'Implementation in lib/cipher/hash/sm3.ts diverges from GB/T 32905-2016 / OpenSSL standard outputs. Divergence detected during independent oracle audit.';
    } else if (isStub) {
      eReason = 'Implementation relies on truncated table stubs and cannot be cryptographically verified.';
    }

    oracleRegistry.algorithms[cipher.id] = {
      id: cipher.id,
      name: cipher.name,
      category: cipher.category,
      primaryOperation: cap.primaryOperation,
      grade: 'E',
      verificationStatus: eStatus,
      standard: 'Literature Reference (Unverified in CryptoViz)',
      section: 'N/A',
      authoritativeVectorSource: 'None',
      independentOracle: 'None',
      oracleVersion: 'N/A',
      testVectorProvenance: 'None',
      inputFormat: 'N/A',
      outputFormat: 'N/A',
      parameters: {},
      evidenceDate: '2026-09-12',
      reason: eReason,
    };
  }
}

// Write oracle registry to file
const outPath = path.resolve('lib/cipher/provenance/oracleRegistry.json');
fs.writeFileSync(outPath, JSON.stringify(oracleRegistry, null, 2), 'utf-8');

// Print grade summary
const counts = { A: 0, B: 0, C: 0, D: 0, E: 0 };
for (const alg of Object.values(oracleRegistry.algorithms)) {
  counts[alg.grade]++;
}

console.log('Successfully built oracleRegistry.json with', Object.keys(oracleRegistry.algorithms).length, 'algorithms.');
console.log('Grade Counts:', counts);
