/**
 * ChaCha20-Poly1305 AEAD — RFC 8439.
 * @see CIPHER_ENGINE.md section "ChaCha20-Poly1305"
 *
 * Pure composition of two already-merged modules (chacha20.ts stream
 * cipher + poly1305.ts one-time MAC) — zero new cryptographic primitives.
 * The software-oriented AEAD alternative to AES-GCM (no hardware AES
 * instructions needed), which is why TLS/WireGuard prefer it on mobile.
 *
 * IMPORTANT: Poly1305's merged contract is generate(message, key) /
 * verify(message, key, tag) — NOT encrypt/decrypt. Written against my
 * best understanding of that contract; verify the actual exported
 * signatures in poly1305.ts and chacha20.ts before relying on this file.
 */

import { encrypt as chacha20Encrypt } from './chacha20'
import { encrypt as poly1305Encrypt } from '../hash/poly1305'
import { CipherError } from '../../utils/errors'
import { constantTimeHexEqual } from '../../utils/constantTime'
import type { CipherResult, CipherStep, CipherMetadata, CipherOptions, TestVector } from '../types'

const METADATA: CipherMetadata = {
  name: 'ChaCha20-Poly1305',
  keySize: 256,
  securityStatus: 'secure',
  yearDesigned: 2014,
  standardBody: 'RFC 8439',
}

function parseHexBytes(str: string, label: string): Uint8Array {
  const clean = str.replace(/\s+/g, '').toLowerCase()
  if (!/^[0-9a-f]*$/.test(clean) || clean.length % 2 !== 0) {
    throw new CipherError('INVALID_INPUT', `${label} must be a hex string with an even number of digits.`)
  }
  const bytes = new Uint8Array(clean.length / 2)
  for (let i = 0; i < bytes.length; i++) bytes[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16)
  return bytes
}
function ciphertextHexToBytes(hex: string): Uint8Array {
  return hex === '' ? new Uint8Array(0) : parseHexBytes(hex, 'ciphertext')
}
function bytesToHex(b: Uint8Array): string {
  return Array.from(b).map((x) => x.toString(16).padStart(2, '0')).join('')
}
function pad16(len: number): Uint8Array {
  const rem = len % 16
  return rem === 0 ? new Uint8Array(0) : new Uint8Array(16 - rem)
}
function le64(n: number): Uint8Array {
  const out = new Uint8Array(8)
  for (let i = 0; i < 8; i++) {
    out[i] = n & 0xff
    n = Math.floor(n / 256)
  }
  return out
}
function concat(chunks: Uint8Array[]): Uint8Array {
  const total = chunks.reduce((s, c) => s + c.length, 0)
  const out = new Uint8Array(total)
  let off = 0
  for (const c of chunks) {
    out.set(c, off)
    off += c.length
  }
  return out
}

import { formatAeadMacInput } from '../aead-utils'

function buildMacInput(aad: Uint8Array, ciphertext: Uint8Array): Uint8Array {
  return formatAeadMacInput(aad, ciphertext)
}

function aeadCore(input: string, key: string, decrypt: boolean, instrument: boolean): CipherResult {
  const start = performance.now()
  const parts = key.split('|')
  const keyHex = parts[0]
  const nonceHex = parts[1] || ''
  const aadHex = parts[2] || ''
  const aad = aadHex ? parseHexBytes(aadHex, 'AAD') : new Uint8Array(0)

  const steps: CipherStep[] = []

  // ChaCha20 with counter=0 to derive the one-time Poly1305 key from the
  // first 32 bytes of the keystream block. Check chacha20.ts's actual
  // counter-parameter mechanism — chacha20.ts uses "key|nonce:counter".
  const zeroBlock = '00'.repeat(64)
  const polyKeyDerivation = chacha20Encrypt(zeroBlock, `${keyHex}|${nonceHex}:0`, { encoding: 'hex' })
  // The first 32 bytes of the block generated by ChaCha20 with counter 0 are used as the Poly1305 key.
  const polyKeyHex = polyKeyDerivation.output.slice(0, 64)

  if (instrument) {
    steps.push({
      index: 0,
      label: 'Derive one-time Poly1305 key',
      inputState: `${keyHex}|nonce=${nonceHex}, counter=0`,
      outputState: polyKeyHex,
      note: 'First 32 bytes of the ChaCha20 keystream (counter=0) become a Poly1305 key used for THIS MESSAGE ONLY — reusing it elsewhere breaks Poly1305.',
      isMilestone: true,
    })
  }

  if (!decrypt) {
    // Encrypt starting at counter=1.
    const ctResult = input === '' ? { output: '', outputEncoding: 'hex' as const, steps: [], metadata: METADATA, durationMs: 0 } : chacha20Encrypt(input, `${keyHex}|${nonceHex}:1`, { encoding: 'hex' })
    const ciphertext = ciphertextHexToBytes(ctResult.output)

    const macInput = buildMacInput(aad, ciphertext)
    const tagResult = poly1305Encrypt(bytesToHex(macInput), polyKeyHex, { encoding: 'hex' })
    const tag = tagResult.output

    if (instrument) {
      steps.push({
        index: 1,
        label: 'ChaCha20 encryption (counter starts at 1)',
        inputState: input,
        outputState: ctResult.output,
        isMilestone: true,
        note: 'Plaintext XORed with keystream starting from block counter 1.',
      })
      steps.push({
        index: 2,
        label: 'Poly1305 tag over (AAD || ciphertext || lengths)',
        inputState: bytesToHex(macInput),
        outputState: tag,
        isMilestone: true,
        note: 'Poly1305 MAC computed over AAD, ciphertext, and their lengths.',
      })
    }

    return {
      output: `${ctResult.output}|${tag}`,
      outputEncoding: 'utf8',
      steps,
      metadata: METADATA,
      durationMs: performance.now() - start,
    }
  } else {
    const pipeIndex = input.indexOf('|')
    if (pipeIndex === -1) {
      throw new CipherError('INVALID_INPUT', 'Expected "ciphertextHex|tagHex".')
    }
    const ciphertextHex = input.slice(0, pipeIndex)
    const receivedTag = input.slice(pipeIndex + 1)
    if (!receivedTag) {
      throw new CipherError('INVALID_INPUT', 'Expected "ciphertextHex|tagHex".')
    }
    const ciphertext = ciphertextHexToBytes(ciphertextHex)
    const macInput = buildMacInput(aad, ciphertext)

    // Verify the tag BEFORE decrypting/returning any plaintext.
    const tagResult = poly1305Encrypt(bytesToHex(macInput), polyKeyHex, { encoding: 'hex' })
    const valid = constantTimeHexEqual(tagResult.output, receivedTag)

    if (instrument) {
      steps.push({
        index: 1,
        label: 'Verify tag before decrypting anything',
        inputState: receivedTag,
        outputState: valid ? 'MATCH' : 'MISMATCH',
        note: 'Tag is checked BEFORE any plaintext is produced — a decrypt-then-verify contract, not verify-after-returning-data.',
        isMilestone: true,
      })
    }
    if (!valid) {
      throw new CipherError('INVALID_INPUT', 'ChaCha20-Poly1305 tag verification failed — ciphertext, AAD, or key/nonce does not match.')
    }

    const ptResult = ciphertextHex === '' ? { output: '', outputEncoding: 'hex' as const, steps: [], metadata: METADATA, durationMs: 0 } : chacha20Encrypt(ciphertextHex, `${keyHex}|${nonceHex}:1`, { encoding: 'hex' })
    if (instrument) {
      steps.push({
        index: 2,
        label: 'ChaCha20 decryption (counter starts at 1)',
        inputState: ciphertextHex,
        outputState: ptResult.output,
        isMilestone: true,
        note: 'Ciphertext XORed with keystream to recover plaintext.',
      })
    }

    return {
      output: ptResult.output,
      outputEncoding: 'hex',
      steps,
      metadata: METADATA,
      durationMs: performance.now() - start,
    }
  }
}

/**
 * Encrypt cipher-engine utility export.
 *
 * This API is intentionally documented at the engine boundary so callers
 * can understand the input contract without opening the implementation.
 * @param input Input required by the Encrypt operation.
 * @param key Input required by the Encrypt operation.
 * @param options Input required by the Encrypt operation.
 * @returns The operation result produced by the cipher engine.
 * @see https://csrc.nist.gov/pubs/fips/197/final — FIPS 197.
 */
export function encrypt(input: string, key: string, options: CipherOptions = {}): CipherResult {
  return aeadCore(input, key, false, !!options.instrument)
}
/**
 * Decrypt cipher-engine utility export.
 *
 * This API is intentionally documented at the engine boundary so callers
 * can understand the input contract without opening the implementation.
 * @param input Input required by the Decrypt operation.
 * @param key Input required by the Decrypt operation.
 * @param options Input required by the Decrypt operation.
 * @returns The operation result produced by the cipher engine.
 * @see https://csrc.nist.gov/pubs/fips/197/final — FIPS 197.
 */
export function decrypt(input: string, key: string, options: CipherOptions = {}): CipherResult {
  return aeadCore(input, key, true, !!options.instrument)
}

/**
 * TEST VECTORS cipher-engine utility export.
 *
 * This API is intentionally documented at the engine boundary so callers
 * can understand the input contract without opening the implementation.
 * @returns The operation result produced by the cipher engine.
 * @see https://csrc.nist.gov/pubs/fips/197/final — FIPS 197.
 */
export const TEST_VECTORS: TestVector[] = [
  {
    input: '4c616469657320616e642047656e746c656d656e206f662074686520636c617373206f66202739393a204966204920636f756c64206f6666657220796f75206f6e6c79206f6e652074697020666f7220746865206675747572652c2073756e73637265656e20776f756c642062652069742e',
    key: '808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f|070000004041424344454647|50515253c0c1c2c3c4c5c6c7',
    expected: 'd31a8d34648e60db7b86afbc53ef7ec2a4aded51296e08fea9e2b5a736ee62d63dbea45e8ca9671282fafb69da92728b1a71de0a9e060b2905d6a5b67ecd3b3692ddbd7f2d778b8c9803aee328091b58fab324e4fad675945585808b4831d7bc3ff4def08e4b7a9de576d26586cec64b6116|1ae10b594f09e26a7e902ecbd0600691',
    description: 'RFC 8439 Section 2.8.2 AEAD Test Vector',
  }
]
